spring:
  profiles:    active: local #local, dev, real → 운영환경 지정

  mvc:    view: #view 경로 및 확장자 지정      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource: #DB 접속    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: c##user001
    password: 1234
    hikari:      connection-timeout: 30000 #client가 pool에 connection을 요청하는데 기다리는 최대시간 설정(30초)
      maximum-pool-size: 10 #최대 connection 개수 설정
      max-lifetime: 1800000 #connection pool에서 살아있을 수 있는 connection의 최대 수명 시간 1,800초(30분)

  messages: #message    basename: messages.validation
    encoding: UTF-8

  devtools: #view reload    livereload:      enabled: true
    restart: #controller, model단이 바뀌었을 때 프로젝트 재시작 설정(Classpath에 있는 모든 파일)      enabled: true

  servlet:    multipart:      max-file-size: 50MB #파일 1개당 최대 크기
      max-request-size: 200MB #요청당 최대 파일 크기

mybatis: #mybatis 설정  type-aliases-package: kr.spring.**.vo
  mapper-locations: kr/spring/**/dao/*.xml

logging: #Log 지정  level:
    '[kr.spring]': debug

server:  port: 8000
  servlet:
    encoding:      charset: UTF-8
      enabled: true #http encoding 지원 활성화 여부(charset의 option)
      force: true #charset의 option
